# Generated by Django 3.0.6 on 2020-07-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
