# Generated by Django 3.0.6 on 2020-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='usuarios/perfis'),
        ),
    ]
